language: cpp
git:
  depth: 1
root: required
dist: xenial

install:
- bash ci-scripts/$TRAVIS_OS_NAME/install.sh
script:
- bash ci-scripts/$TRAVIS_OS_NAME/build.sh
jobs:
  include:
  - os: osx
    osx_image: xcode12.0.1
  - os: linux
    compiler: gcc
