name: Build
on:
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
    
jobs:
  build-linux:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          modules: qtcharts
          
      - name: Install dependencies
        run: |
             sudo apt-get update
             sudo apt-get install libgl1-mesa-dev libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 libzstd-dev
        
      - name: Compile
        run: |
             qmake Serial-Studio.pro CONFIG+=release PREFIX=/usr
             make
             make INSTALL_ROOT=appdir install
             
      - name: Create AppImage
        run: | 
             wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" -O linuxdeployqt
             chmod a+x linuxdeployqt
             ./linuxdeployqt appdir/usr/share/applications/*.desktop -appimage -bundle-non-qt-libs -extra-plugins=imageformats/libqsvg.so -qmldir=../assets/qml
             ./linuxdeployqt --appimage-extract
             export PATH=$(readlink -f ./squashfs-root/usr/bin/):$PATH
             ./squashfs-root/usr/bin/appimagetool appdir/
             find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
             mv *.AppImage SerialStudio-1.0.5-Linux.AppImage
                
      - name: Upload AppImage
        uses: actions/upload-artifact@v2
        with:
          name: SerialStudio-1.0.5-Linux.AppImage
          path: SerialStudio-1.0.5-Linux.AppImage
             
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          modules: qtcharts
          
      - name: Install create-dmg
        run: brew install create-dmg
                
      - name: Compile
        run: |
             qmake Serial-Studio.pro
             make
             
      - name: Create DMG
        run: |       
             make dmg
             mv *.dmg SerialStudio-1.0.5-macOS.dmg
             
      - name: Upload DMG
        uses: actions/upload-artifact@v2
        with:
          name: SerialStudio-1.0.5-macOS.dmg
          path: SerialStudio-1.0.5-macOS.dmg
